### ISSUE TITLE
Provide recent builds

### ISSUE THREAD

**Issue by ge0rg** [KaidanIM/packages#1]
Hi,

I've followed the Debian Kaidan installation instructions in https://github.com/KaidanIM/Kaidan/blob/master/README.md and ended up with version 0.2.3, which looks rather basic. Then I realized that on GitHub you already have 0.3.2.

Please either update the debian packages or change the README accordingly.

**Comment by jbruechert** [comment]
You are right, our binary packages are currently rather outdated for the reason we lost our gpg signing key. I'll set up a repo with a new key soon. For  now, please build Kaidan using cmake.

**Comment by lnjX** [comment]
Just FYI, the new version won't be stretch compatible, unfortunately.

**Comment by jbruechert** [comment]
Updated builds are now available for debian sid. The README of the main repository https://github.com/KaidanIM/kaidan has been updated.
